version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/answer_db
      - JWT_SECRET=secret
      - OPENAI_MODEL=gpt-3.5-turbo-instruct
      - OPENAI_API_KEY=your-openai-api-key
    depends_on:
      - db

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: answer_db
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  db_data:
